In [51]:
import numpy as np
import pandas as pd

In [21]:
df = pd.read_csv('energydata_complete.csv')
df.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [22]:
df.columns

Index(['date', 'Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3',
       'RH_3', 'T4', 'RH_4', 'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8',
       'RH_8', 'T9', 'RH_9', 'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed',
       'Visibility', 'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [23]:
cols = {
    'T1':'kitchen-Temp(T1)', 'RH_1': 'kitchen-Humid(RH_1)', 'T2': 'living_room-Temp(T2)', 'RH_2': 'living_room-Humid(RH_2)',
    'T3': 'laundry_room-Temp(T3)', 'RH_3': 'laundry_room-Humod(RH_3)', 'T4': 'office_room-Temp(T4)', 'RH_4': 'office_room-Humid(RH_4)',
    'T5': 'bathroom-Temp(T5)', 'RH_5': 'bathroom-Humid(RH_5)', 'T6': 'outside_north-Temp(T6)', 'RH_6': 'outside_north-Humid(RH_6)',
    'T7': 'ironing_room-Temp(T7)', 'RH_7': 'ironing_room-Temp(RH_7)', 'T8': 'teenager_room_2-Temp(T8)', 'RH_8': 'teenager_room_2-Humid(RH_8)',
    'T9': 'parents_room-Temp(T9)', 'RH_9': 'parents_room-Humid(RH_9)', 'To': 'outside-Temp(Chievres weather station)', 
    'RH_out': 'outside-Humid(Chievres weather station)', 'rv1': 'Random_variable_1(nondimensiona)', 'rv2': 'Random_variable_2(nondimensional)'
}

In [24]:
df.rename(columns=cols, inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 29 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   date                                     19735 non-null  object
 1   Appliances                               19735 non-null  int64
 2   lights                                   19735 non-null  int64
 3   kitchen-Temp(T1)                         19735 non-null  float64
 4   kitchen-Humid(RH_1)                      19735 non-null  float64
 5   living_room-Temp(T2)                     19735 non-null  float64
 6   living_room-Humid(RH_2)                  19735 non-null  float64
 7   laundry_room-Temp(T3)                    19735 non-null  float64
 8   laundry_room-Humod(RH_3)                 19735 non-null  float64
 9   office_room-Temp(T4)                     19735 non-null  float64
 10  office_room-Humid(RH_4)                  19735 non-null  float64
 11  bathroom-Temp(T5)                        19735 non-null  float64
 12  bathroom-Humid(RH_5)                     19735 non-null  float64
 13  outside_north-Temp(T6)                   19735 non-null  float64
 14  outside_north-Humid(RH_6)                19735 non-null  float64
 15  ironing_room-Temp(T7)                    19735 non-null  float64
 16  ironing_room-Temp(RH_7)                  19735 non-null  float64
 17  teenager_room_2-Temp(T8)                 19735 non-null  float64
 18  teenager_room_2-Humid(RH_8)              19735 non-null  float64
 19  parents_room-Temp(T9)                    19735 non-null  float64
 20  parents_room-Humid(RH_9)                 19735 non-null  float64
 21  T_out                                    19735 non-null  float64
 22  Press_mm_hg                              19735 non-null  float64
 23  outside-Humid(Chievres weather station)  19735 non-null  float64
 24  Windspeed                                19735 non-null  float64
 25  Visibility                               19735 non-null  float64
 26  Tdewpoint                                19735 non-null  float64
 27  Random_variable_1(nondimensiona)         19735 non-null  float64
 28  Random_variable_2(nondimensional)        19735 non-null  float64
dtypes: float64(26), int64(2), object(1)
memory usage: 4.4+ MB

In [26]:
df.describe()

,Appliances,lights,kitchen-Temp(T1),kitchen-Humid(RH_1),living_room-Temp(T2),living_room-Humid(RH_2),laundry_room-Temp(T3),laundry_room-Humod(RH_3),office_room-Temp(T4),office_room-Humid(RH_4),...,parents_room-Temp(T9),parents_room-Humid(RH_9),T_out,Press_mm_hg,outside-Humid(Chievres weather station),Windspeed,Visibility,Tdewpoint,Random_variable_1(nondimensiona),Random_variable_2(nondimensional)
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,3.801875,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,7.935988,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,0.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,0.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,0.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,0.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,70.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [40]:
from sklearn.preprocessing import MinMaxScaler
SCALE = MinMaxScaler()
df = df.drop('date', axis=1)
norm = pd.DataFrame(SCALE.fit_transform(df), columns=df.columns)

In [60]:
x = norm.drop(columns=['lights'])
y = norm['Appliances']

In [68]:
X_train, X_test, y_train, y_test = train_test_split( x,y, test_size=0.3)

In [69]:
print(X_train)

       Appliances  kitchen-Temp(T1)  kitchen-Humid(RH_1)  \
7078     0.084112          0.510560             0.230529
7376     0.046729          0.553678             0.276397
7787     0.074766          0.353045             0.350702
13496    0.074766          0.485744             0.400055
17211    0.046729          0.866948             0.488304
...           ...               ...                  ...
18865    0.093458          0.861140             0.528988
9994     0.037383          0.538543             0.285570
2278     0.018692          0.313622             0.522246
966      0.028037          0.307286             0.389139
16305    0.037383          0.644139             0.219521

       living_room-Temp(T2)  living_room-Humid(RH_2)  laundry_room-Temp(T3)  \
7078               0.247153                 0.463961               0.422898
7376               0.338745                 0.464992               0.306580
7787               0.157015                 0.578217               0.306580
13496              0.397383                 0.586653               0.464440
17211              0.516113                 0.727247               0.772682
...                     ...                      ...                    ...
18865              0.654228                 0.617771               0.768112
9994               0.202811                 0.575593               0.407112
2278               0.202811                 0.709626               0.229589
966                0.145384                 0.599681               0.219342
16305              0.340926                 0.421876               0.481888

       laundry_room-Humod(RH_3)  office_room-Temp(T4)  \
7078                   0.277302              0.540240
7376                   0.459106              0.515616
7787                   0.332918              0.287387
13496                  0.445085              0.720721
17211                  0.549213              0.918018
...                         ...                   ...
18865                  0.585761              0.819820
9994                   0.374981              0.422523
2278                   0.766319              0.315315
966                    0.559822              0.360360
16305                  0.343979              0.675676

       office_room-Humid(RH_4)  bathroom-Temp(T5)  ...  parents_room-Temp(T9)  \
7078                  0.264618           0.279981  ...               0.364204
7376                  0.328638           0.330626  ...               0.334027
7787                  0.348841           0.255136  ...               0.344433
13496                 0.546593           0.483516  ...               0.607700
17211                 0.635297           0.780698  ...               0.936524
...                        ...                ...  ...                    ...
18865                 0.740077           0.747253  ...               0.854318
9994                  0.389671           0.398471  ...               0.490114
2278                  0.833974           0.207358  ...               0.229969
966                   0.439892           0.244625  ...               0.249740
16305                 0.261630           0.569517  ...               0.561915

       parents_room-Humid(RH_9)     T_out  Press_mm_hg  \
7078                   0.373896  0.176849     0.797674
7376                   0.307257  0.241158     0.353488
7787                   0.285320  0.252412     0.331395
13496                  0.459161  0.460879     0.586047
17211                  0.858168  0.633441     0.515116
...                         ...       ...          ...
18865                  0.713300  0.901929     0.572868
9994                   0.456678  0.300107     0.741085
2278                   0.816777  0.516613     0.637984
966                    0.399834  0.048232     0.697674
16305                  0.341198  0.398714     0.854651

       outside-Humid(Chievres weather station)  Windspeed  Visibility  \
7078                                  0.723684   0.166667    0.343590
7376                                  0.820175   0.571429    0.533333
7787                                  0.734649   0.214286    0.600000
13496                                 0.811404   0.142857    0.758974
17211                                 0.953947   0.142857    0.338462
...                                        ...        ...         ...
18865                                 0.339912   0.488095    0.600000
9994                                  0.934211   0.095238    0.841026
2278                                  0.776316   0.761905    0.543590
966                                   0.828947   0.071429    0.338462
16305                                 0.638158   0.071429    0.600000

       Tdewpoint  Random_variable_1(nondimensiona)  \
7078    0.176471                          0.985158
7376    0.318250                          0.293541
7787    0.282805                          0.242183
13496   0.615385                          0.772272
17211   0.938914                          0.649938
...          ...                               ...
18865   0.845400                          0.039859
9994    0.461538                          0.244361
2278    0.672700                          0.246831
966     0.054299                          0.358586
16305   0.416290                          0.816339

       Random_variable_2(nondimensional)
7078                            0.985158
7376                            0.293541
7787                            0.242183
13496                           0.772272
17211                           0.649938
...                                  ...
18865                           0.039859
9994                            0.244361
2278                            0.246831
966                             0.358586
16305                           0.816339

[13814 rows x 27 columns]

In [70]:
lin_model = LinearRegression()
lin_model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [71]:
prediction = lin_model.predict(X_test)
prediction

array([0.02803738, 0.03738318, 0.11214953, ..., 0.01869159, 0.03738318,
       0.03738318])

In [72]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, prediction)
round(mae, 2)

0.0

In [73]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, prediction)
round(r2, 3)

1.0

In [74]:
rss = np.sum(np.square(y_test - prediction))
round(rss, 2)

0.0